name = "doppler_effect"
description = "Moving airplane causes Stereo Sound Doppler effect."
version = "0.1.0-dev"

authors = ["moriyasum"]
maintainers = ["Manuel Gomez <mgrojo@gmail.com>"]
maintainers-logins = ["mgrojo"]

executables = ["main"]
[[depends-on]]
gtkada = "^21.0.0"
